// file generated by the Paraglide-Next init command
import { createI18n } from "@inlang/paraglide-next";
import type { AvailableLanguageTag } from "@/paraglide/runtime";

export const {
  Link,
  middleware,
  useRouter,
  usePathname,
  redirect,
  permanentRedirect,
  localizePath,
} = createI18n<AvailableLanguageTag>({
  prefix: "all",
  pathnames: {
    "/properties/[...rest]": {
      en: "/properties/[...rest]",
      "pt-br": "/propriedades/[...rest]",
    },
    "/properties/custom": {
      en: "/properties/custom",
      "pt-br": "/propriedades/customizado",
    },
  },
});
